import {  Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/footer/footer";
import Totop from "../components/Totop/page.jsx";
import Cart from "../components/cart/cart";
import Cartecontext from "@/context/cartecontext";

const mont = Montserrat({ subsets: ["latin"]});

export const metadata = {
  title: "FooDev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={mont.className}>

        <Cartecontext>

        <Cart/>
        <Header/>
        {children}
        </Cartecontext>
        
        <Footer/>
        <Totop/>

        
        </body>
    </html>
  );
}
